name: baixinglive
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_swiper_null_safety: ^1.0.2
  dio: ^5.8.0
  provider: ^6.0.5
  go_router: ^15.1.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.11
  flutter_svg: ^2.0.7
  window_manager: ^0.4.3
  webview_flutter: ^4.11.0
  permission_handler: ^12.0.0+1
  flutter_debouncer: ^2.0.0
  shared_preferences: ^2.5.3
  flutter_vibrate: ^1.3.0
  custom_sliding_segmented_control: ^1.8.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - images/baixing_weixin.webp
    - images/baixing_99zhibo_text.webp
    - images/baixing_qq.webp
    - images/baixing_bg_jianbian.png
    - images/baixing_logo.svg
    - images/baixing_99.webp
    - images/baixing_logo.webp
    - images/baixing_weibo.webp
    - images/baixing_girl_xxxl.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
